"""add_organization_wide_defaults_model

Revision ID: ec7fcf6bb2dc
Revises: defb84c530e8
Create Date: 2026-04-28 21:00:28.882081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec7fcf6bb2dc'
down_revision: Union[str, None] = 'defb84c530e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_wide_default_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('sobject_type', sa.String(length=100), nullable=False),
    sa.Column('sobject_label', sa.String(length=255), nullable=True),
    sa.Column('internal_sharing_model', sa.String(length=50), nullable=False),
    sa.Column('external_sharing_model', sa.String(length=50), nullable=True),
    sa.Column('is_default_owner_is_creator', sa.Boolean(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'sobject_type', 'snapshot_date', name='uq_owd_org_sobject_snapshot')
    )
    op.create_index('ix_owd_org', 'organization_wide_default_snapshots', ['organization_id'], unique=False)
    op.create_index('ix_owd_sobject', 'organization_wide_default_snapshots', ['sobject_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_owd_sobject', table_name='organization_wide_default_snapshots')
    op.drop_index('ix_owd_org', table_name='organization_wide_default_snapshots')
    op.drop_table('organization_wide_default_snapshots')
    # ### end Alembic commands ###
