"""add_org_user_rbac_model

Revision ID: 7df734125b01
Revises: f2d1f34d59c8
Create Date: 2026-05-01 18:07:44.034767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '7df734125b01'
down_revision: Union[str, None] = 'f2d1f34d59c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ORG_ADMIN', 'ANALYST', 'VIEWER', 'AUDITOR', name='orguserrole', native_enum=False, length=20), nullable=False),
    sa.Column('can_export_data', sa.Boolean(), nullable=False),
    sa.Column('can_manage_users', sa.Boolean(), nullable=False),
    sa.Column('can_sync_data', sa.Boolean(), nullable=False),
    sa.Column('can_delete_data', sa.Boolean(), nullable=False),
    sa.Column('can_view_audit_logs', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('invited_by', sa.String(length=36), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'email', name='uq_org_user_email')
    )
    op.create_index('ix_org_user_email', 'org_users', ['email'], unique=False)
    op.create_index('ix_org_user_org', 'org_users', ['organization_id'], unique=False)
    op.create_index('ix_org_user_role', 'org_users', ['role'], unique=False)
    # NOTE: All audit_logs modifications were already done in migration f2d1f34d59c8
    # This migration only adds the org_users table
    # The following operations are commented out to avoid duplicates:
    # - op.alter_column('audit_logs', 'organization_id', ...)
    # - op.alter_column('audit_logs', 'action', ...)
    # - op.create_index('ix_audit_created', ...)
    # - op.create_index('ix_audit_resource', ...)
    # - op.create_index('ix_audit_user', ...)
    # - op.drop_column('audit_logs', 'timestamp')
    # - op.drop_column('audit_logs', 'actor')
    # - op.drop_column('audit_logs', 'details')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: All audit_logs downgrades were already done in migration f2d1f34d59c8
    # This migration only removes the org_users table
    op.drop_index('ix_org_user_role', table_name='org_users')
    op.drop_index('ix_org_user_org', table_name='org_users')
    op.drop_index('ix_org_user_email', table_name='org_users')
    op.drop_table('org_users')
    # ### end Alembic commands ###
