"""add_org_user_rbac_model

Revision ID: 7df734125b01
Revises: f2d1f34d59c8
Create Date: 2026-05-01 18:07:44.034767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '7df734125b01'
down_revision: Union[str, None] = 'f2d1f34d59c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ORG_ADMIN', 'ANALYST', 'VIEWER', 'AUDITOR', name='orguserrole', native_enum=False, length=20), nullable=False),
    sa.Column('can_export_data', sa.Boolean(), nullable=False),
    sa.Column('can_manage_users', sa.Boolean(), nullable=False),
    sa.Column('can_sync_data', sa.Boolean(), nullable=False),
    sa.Column('can_delete_data', sa.Boolean(), nullable=False),
    sa.Column('can_view_audit_logs', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('invited_by', sa.String(length=36), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'email', name='uq_org_user_email')
    )
    op.create_index('ix_org_user_email', 'org_users', ['email'], unique=False)
    op.create_index('ix_org_user_org', 'org_users', ['organization_id'], unique=False)
    op.create_index('ix_org_user_role', 'org_users', ['role'], unique=False)
    op.alter_column('audit_logs', 'organization_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('LOGIN', 'LOGOUT', 'VIEW_USERS', 'VIEW_USER_DETAILS', 'VIEW_PERMISSIONS', 'VIEW_ACCESS_GRAPH', 'VIEW_ANOMALIES', 'VIEW_RECOMMENDATIONS', 'SYNC_DATA', 'DELETE_DATA', 'EXPORT_DATA', 'UPDATE_SETTINGS', 'INVITE_USER', 'REMOVE_USER', 'UPDATE_USER_ROLE', 'CONNECT_SALESFORCE', 'DISCONNECT_SALESFORCE', name='auditaction', native_enum=False, length=50),
               existing_nullable=False)
    # Drop index only if it exists (may not exist in production DB)
    try:
        op.drop_index(op.f('ix_audit_timestamp'), table_name='audit_logs')
    except Exception:
        pass  # Index doesn't exist, continue
    op.create_index('ix_audit_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_user', 'audit_logs', ['user_email'], unique=False)
    op.drop_column('audit_logs', 'timestamp')
    op.drop_column('audit_logs', 'actor')
    op.drop_column('audit_logs', 'details')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('details', sqlite.JSON(), nullable=False))
    op.add_column('audit_logs', sa.Column('actor', sa.VARCHAR(length=100), nullable=True))
    op.add_column('audit_logs', sa.Column('timestamp', sa.DATETIME(), nullable=False))
    op.drop_index('ix_audit_user', table_name='audit_logs')
    op.drop_index('ix_audit_resource', table_name='audit_logs')
    op.drop_index('ix_audit_created', table_name='audit_logs')
    op.create_index(op.f('ix_audit_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.Enum('LOGIN', 'LOGOUT', 'VIEW_USERS', 'VIEW_USER_DETAILS', 'VIEW_PERMISSIONS', 'VIEW_ACCESS_GRAPH', 'VIEW_ANOMALIES', 'VIEW_RECOMMENDATIONS', 'SYNC_DATA', 'DELETE_DATA', 'EXPORT_DATA', 'UPDATE_SETTINGS', 'INVITE_USER', 'REMOVE_USER', 'UPDATE_USER_ROLE', 'CONNECT_SALESFORCE', 'DISCONNECT_SALESFORCE', name='auditaction', native_enum=False, length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('audit_logs', 'organization_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_index('ix_org_user_role', table_name='org_users')
    op.drop_index('ix_org_user_org', table_name='org_users')
    op.drop_index('ix_org_user_email', table_name='org_users')
    op.drop_table('org_users')
    # ### end Alembic commands ###
