"""add_field_encryption_support

Adds AES-256 field-level encryption support for sensitive data.

NOTE: This migration does not alter the database schema because encryption is
handled at the application level using SQLAlchemy-Utils EncryptedType.

The following fields are now encrypted when ENABLE_FIELD_ENCRYPTION=True:
- SalesforceConnection.access_token (OAuth access tokens)
- SalesforceConnection.refresh_token (OAuth refresh tokens)

Encryption is transparent to the database - encrypted data is stored as TEXT
and automatically encrypted/decrypted by the application layer.

Also fixes group_snapshots.name to be non-nullable.

Revision ID: 31b86119bef3
Revises: ec7fcf6bb2dc
Create Date: 2026-04-30 23:24:02.383024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31b86119bef3'
down_revision: Union[str, None] = 'ec7fcf6bb2dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table('group_snapshots', schema=None) as batch_op:
        batch_op.alter_column('name',
                   existing_type=sa.VARCHAR(length=255),
                   nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table('group_snapshots', schema=None) as batch_op:
        batch_op.alter_column('name',
                   existing_type=sa.VARCHAR(length=255),
                   nullable=True)
    # ### end Alembic commands ###
