"""add_comprehensive_audit_log_model

Revision ID: f2d1f34d59c8
Revises: bf23e62611eb
Create Date: 2026-05-01 17:47:28.978203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'f2d1f34d59c8'
down_revision: Union[str, None] = 'bf23e62611eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('user_email', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.add_column('audit_logs', sa.Column('resource_type', sa.String(length=100), nullable=False))
    op.add_column('audit_logs', sa.Column('resource_id', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('audit_logs', sa.Column('user_agent', sa.String(length=500), nullable=True))
    op.add_column('audit_logs', sa.Column('request_path', sa.String(length=500), nullable=True))
    op.add_column('audit_logs', sa.Column('request_method', sa.String(length=10), nullable=True))
    op.add_column('audit_logs', sa.Column('success', sa.Boolean(), nullable=False))
    op.add_column('audit_logs', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('audit_logs', sa.Column('context_data', sa.JSON(), nullable=False))
    op.alter_column('audit_logs', 'organization_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('LOGIN', 'LOGOUT', 'VIEW_USERS', 'VIEW_USER_DETAILS', 'VIEW_PERMISSIONS', 'VIEW_ACCESS_GRAPH', 'VIEW_ANOMALIES', 'VIEW_RECOMMENDATIONS', 'SYNC_DATA', 'DELETE_DATA', 'EXPORT_DATA', 'UPDATE_SETTINGS', 'INVITE_USER', 'REMOVE_USER', 'UPDATE_USER_ROLE', 'CONNECT_SALESFORCE', 'DISCONNECT_SALESFORCE', name='auditaction', native_enum=False, length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_audit_timestamp'), table_name='audit_logs')
    op.create_index('ix_audit_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_user', 'audit_logs', ['user_email'], unique=False)
    op.drop_column('audit_logs', 'actor')
    op.drop_column('audit_logs', 'details')
    op.drop_column('audit_logs', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('timestamp', sa.DATETIME(), nullable=False))
    op.add_column('audit_logs', sa.Column('details', sqlite.JSON(), nullable=False))
    op.add_column('audit_logs', sa.Column('actor', sa.VARCHAR(length=100), nullable=True))
    op.drop_index('ix_audit_user', table_name='audit_logs')
    op.drop_index('ix_audit_resource', table_name='audit_logs')
    op.drop_index('ix_audit_created', table_name='audit_logs')
    op.create_index(op.f('ix_audit_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.Enum('LOGIN', 'LOGOUT', 'VIEW_USERS', 'VIEW_USER_DETAILS', 'VIEW_PERMISSIONS', 'VIEW_ACCESS_GRAPH', 'VIEW_ANOMALIES', 'VIEW_RECOMMENDATIONS', 'SYNC_DATA', 'DELETE_DATA', 'EXPORT_DATA', 'UPDATE_SETTINGS', 'INVITE_USER', 'REMOVE_USER', 'UPDATE_USER_ROLE', 'CONNECT_SALESFORCE', 'DISCONNECT_SALESFORCE', name='auditaction', native_enum=False, length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('audit_logs', 'organization_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_column('audit_logs', 'context_data')
    op.drop_column('audit_logs', 'error_message')
    op.drop_column('audit_logs', 'success')
    op.drop_column('audit_logs', 'request_method')
    op.drop_column('audit_logs', 'request_path')
    op.drop_column('audit_logs', 'user_agent')
    op.drop_column('audit_logs', 'ip_address')
    op.drop_column('audit_logs', 'resource_id')
    op.drop_column('audit_logs', 'resource_type')
    op.drop_column('audit_logs', 'user_id')
    op.drop_column('audit_logs', 'user_email')
    # ### end Alembic commands ###
