"""add_record_level_sharing_models

Revision ID: e2af425a8407
Revises: 001
Create Date: 2026-04-16 21:53:52.076350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2af425a8407'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_share_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('salesforce_id', sa.String(length=18), nullable=False),
    sa.Column('account_id', sa.String(length=18), nullable=False),
    sa.Column('user_or_group_id', sa.String(length=18), nullable=False),
    sa.Column('account_access_level', sa.String(length=20), nullable=False),
    sa.Column('opportunity_access_level', sa.String(length=20), nullable=False),
    sa.Column('case_access_level', sa.String(length=20), nullable=False),
    sa.Column('row_cause', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'salesforce_id', 'snapshot_date', name='uq_account_share_org_sf_snapshot')
    )
    op.create_index('ix_account_share_account', 'account_share_snapshots', ['account_id'], unique=False)
    op.create_index('ix_account_share_cause', 'account_share_snapshots', ['row_cause'], unique=False)
    op.create_index('ix_account_share_org', 'account_share_snapshots', ['organization_id'], unique=False)
    op.create_index('ix_account_share_user', 'account_share_snapshots', ['user_or_group_id'], unique=False)
    op.create_table('account_team_member_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('salesforce_id', sa.String(length=18), nullable=False),
    sa.Column('account_id', sa.String(length=18), nullable=False),
    sa.Column('user_id', sa.String(length=18), nullable=False),
    sa.Column('team_member_role', sa.String(length=100), nullable=True),
    sa.Column('account_access_level', sa.String(length=20), nullable=True),
    sa.Column('opportunity_access_level', sa.String(length=20), nullable=True),
    sa.Column('case_access_level', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'salesforce_id', 'snapshot_date', name='uq_account_team_org_sf_snapshot')
    )
    op.create_index('ix_account_team_account', 'account_team_member_snapshots', ['account_id'], unique=False)
    op.create_index('ix_account_team_org', 'account_team_member_snapshots', ['organization_id'], unique=False)
    op.create_index('ix_account_team_user', 'account_team_member_snapshots', ['user_id'], unique=False)
    op.create_table('group_member_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('salesforce_id', sa.String(length=18), nullable=False),
    sa.Column('group_id', sa.String(length=18), nullable=False),
    sa.Column('user_or_group_id', sa.String(length=18), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'salesforce_id', 'snapshot_date', name='uq_group_member_org_sf_snapshot')
    )
    op.create_index('ix_group_member_group', 'group_member_snapshots', ['group_id'], unique=False)
    op.create_index('ix_group_member_org', 'group_member_snapshots', ['organization_id'], unique=False)
    op.create_index('ix_group_member_user', 'group_member_snapshots', ['user_or_group_id'], unique=False)
    op.create_table('group_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('salesforce_id', sa.String(length=18), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('developer_name', sa.String(length=255), nullable=True),
    sa.Column('group_type', sa.String(length=50), nullable=False),
    sa.Column('related_id', sa.String(length=18), nullable=True),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'salesforce_id', 'snapshot_date', name='uq_group_org_sf_snapshot')
    )
    op.create_index('ix_group_org', 'group_snapshots', ['organization_id'], unique=False)
    op.create_index('ix_group_type', 'group_snapshots', ['group_type'], unique=False)
    op.create_table('opportunity_share_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('salesforce_id', sa.String(length=18), nullable=False),
    sa.Column('opportunity_id', sa.String(length=18), nullable=False),
    sa.Column('user_or_group_id', sa.String(length=18), nullable=False),
    sa.Column('opportunity_access_level', sa.String(length=20), nullable=False),
    sa.Column('row_cause', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'salesforce_id', 'snapshot_date', name='uq_opp_share_org_sf_snapshot')
    )
    op.create_index('ix_opp_share_opp', 'opportunity_share_snapshots', ['opportunity_id'], unique=False)
    op.create_index('ix_opp_share_org', 'opportunity_share_snapshots', ['organization_id'], unique=False)
    op.create_index('ix_opp_share_user', 'opportunity_share_snapshots', ['user_or_group_id'], unique=False)
    op.create_table('sharing_rule_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('salesforce_id', sa.String(length=18), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('sobject_type', sa.String(length=100), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('access_level', sa.String(length=50), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=True),
    sa.Column('shared_to_type', sa.String(length=100), nullable=False),
    sa.Column('shared_to_id', sa.String(length=18), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'salesforce_id', 'snapshot_date', name='uq_sharing_rule_org_sf_snapshot')
    )
    op.create_index('ix_sharing_rule_object', 'sharing_rule_snapshots', ['sobject_type'], unique=False)
    op.create_index('ix_sharing_rule_org', 'sharing_rule_snapshots', ['organization_id'], unique=False)
    op.create_index('ix_sharing_rule_type', 'sharing_rule_snapshots', ['rule_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sharing_rule_type', table_name='sharing_rule_snapshots')
    op.drop_index('ix_sharing_rule_org', table_name='sharing_rule_snapshots')
    op.drop_index('ix_sharing_rule_object', table_name='sharing_rule_snapshots')
    op.drop_table('sharing_rule_snapshots')
    op.drop_index('ix_opp_share_user', table_name='opportunity_share_snapshots')
    op.drop_index('ix_opp_share_org', table_name='opportunity_share_snapshots')
    op.drop_index('ix_opp_share_opp', table_name='opportunity_share_snapshots')
    op.drop_table('opportunity_share_snapshots')
    op.drop_index('ix_group_type', table_name='group_snapshots')
    op.drop_index('ix_group_org', table_name='group_snapshots')
    op.drop_table('group_snapshots')
    op.drop_index('ix_group_member_user', table_name='group_member_snapshots')
    op.drop_index('ix_group_member_org', table_name='group_member_snapshots')
    op.drop_index('ix_group_member_group', table_name='group_member_snapshots')
    op.drop_table('group_member_snapshots')
    op.drop_index('ix_account_team_user', table_name='account_team_member_snapshots')
    op.drop_index('ix_account_team_org', table_name='account_team_member_snapshots')
    op.drop_index('ix_account_team_account', table_name='account_team_member_snapshots')
    op.drop_table('account_team_member_snapshots')
    op.drop_index('ix_account_share_user', table_name='account_share_snapshots')
    op.drop_index('ix_account_share_org', table_name='account_share_snapshots')
    op.drop_index('ix_account_share_cause', table_name='account_share_snapshots')
    op.drop_index('ix_account_share_account', table_name='account_share_snapshots')
    op.drop_table('account_share_snapshots')
    # ### end Alembic commands ###
